In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


using np.zeros() and np.ones()

In [2]:
zeroes_arr=np.zeros((2,3))  #2X3 array 
print(zeroes_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
ones_arr=np.ones((3,2))
print(ones_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
arange_arr=np.arange(0,10,2)
arange_arr

array([0, 2, 4, 6, 8])

In [7]:
linespace_arr=np.linspace(0,1,9)
linespace_arr

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [13]:
random_arr=np.random.rand(3,3)*10
print(random_arr)

[[3.07069563 7.47698392 1.27301225]
 [6.02590956 2.17263775 2.60074717]
 [3.7376827  6.4371425  0.1915347 ]]


In [10]:
arr1=[1,2,3,4]
arr2=arr1[1:3]
print(arr1)


[1, 2, 3, 4]


In [12]:
print(np.random.randint(low=4,size=(2,3)))

[[1 0 0]
 [3 1 1]]


In [21]:
arr4=np.random.randint(low=4,size=(1,3))
# print(arr[1][3])
print(arr4)

[[2 3 0]]


In [22]:
arr5=np.array([1,2,3,4,5,6,7])
print(arr5)

[1 2 3 4 5 6 7]


In [25]:
arr6 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed