In [9]:
import numpy as np
arr=np.array([1,2,3,4,5])
sliced_arr=arr[1:4]
sliced_arr

array([2, 3, 4])

In [10]:
print(sliced_arr)

[2 3 4]


In [12]:
arr2D=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr2D)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [13]:
arrf=np.array([1,2,3,4,5,6],dtype=float)

In [15]:
print(arrf)
arrf2=arrf[1:4]

[1. 2. 3. 4. 5. 6.]


In [16]:
print(arrf2)

[2. 3. 4.]


In [17]:
arr2D[1,1]

7

In [18]:
print(arr2D[0,1:3])

[2 3]


In [22]:
print("This is for range 0:2 :\0")
print(arr2D[0:2,0:2])
print("and this will be for other other range slicing which is 0:3 :\0")
print(arr2D[0:3,0:2])

This is for range 0:2 :
[[1 2]
 [6 7]]
and this will be for other other range slicing which is 0:3 :
[[ 1  2]
 [ 6  7]
 [11 12]]


In [31]:
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[23,24,25],[26,27,28]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [23 24 25]
  [26 27 28]]]


In [32]:
print(arr3d[1,1,1])

14


In [35]:
print(arr3d[0:3,1,0:2])

[[ 4  5]
 [13 14]
 [23 24]]


In [38]:
print(arr3d[0:,0:,2])

[[ 3  6  9]
 [12 15 18]
 [21 25 28]]


In [42]:
arr2=np.array([2,3,4,5])
arr3=np.copy(arr2)
arr4=arr2[1:]
arr4

array([3, 4, 5])

In [43]:
arr2=np.array([1,2,3])
copy_arr=np.copy(arr2)
print(copy_arr)

[1 2 3]


In [52]:
arr3=np.array([1,2,3])
arr_view=arr.view()
arr_copy=arr.copy()
print(arr_copy)
print(arr_view)
print(arr_copy.base)


[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
None


In [53]:
arr_view.base

array([1, 2, 3, 4, 5])