In [1]:
#include<stdio.h>
def numbers(num):
    print(num)
numbers(5)

5


In [3]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr.ndim)
print(arr.size)

(2, 4)
2
8


In [5]:
arr1=np.arange(1,10)
reshaped_arr=arr1.reshape((3,-1))

In [6]:
reshaped_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
rehshape=arr2.reshape((2,-1))

In [12]:
print(rehshape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [17]:
reshaped_arr1=arr2.reshape(3,-2)
print(reshaped_arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
reshaped_arr2=arr2.reshape(2,2,-1)
print(reshaped_arr2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
reshaped_arr3=reshaped_arr1.reshape(-1)
print(reshaped_arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [20]:
arr3=np.array([1,2,3,4,5,6,7])
for i in arr3:
    print(i)

1
2
3
4
5
6
7


In [23]:
arr2D=np.array([[1,2,4,5,5],[6,7,8,9,10],[11,12,13,14,15]])
for i in arr2D:
    print(i)

[1 2 4 5 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [24]:
for i in np.nditer(arr2D):
    print(i)

1
2
4
5
5
6
7
8
9
10
11
12
13
14
15


In [25]:
sin_arr=np.sin(arr3)
print(sin_arr)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866 ]


In [26]:
matrix_a=np.array([[1,2],[3,4]])
matrix_b=np.array([[5,6],[7,8]])
result=np.dot(matrix_a,matrix_b)
print(result)

[[19 22]
 [43 50]]


In [ ]:
matrix_c=np.array([[1,2],[3,4]])


"""Tasks"""
1. searching an element an element in an array.
2. Finding largest number in an array
3. Finding smalleset number in an array.
4. Reversing an array
5. Rotating an array by kth position